name: Tests for delight Spot

on: pull_request

jobs:
  Delight-Spot-Tests:
    name: Tests for Next.js app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: npm run test
